apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: testcronjob
  namespace: argocd
spec:
  destination:
    name: ''
    namespace: default
    server: 'https://kubernetes.default.svc'
  sources:
    - chart: external-dns
      repoURL: 'https://github.com/loic-darras/test-lds-packaging'
      targetRevision: HEAD
  project: default
  syncPolicy:
    automated:
      prune: true
      selfHeal: true