# yaml-language-server: $schema=values.schema.json
nameOverride: my-component
deployment:
  id: d929a392
  subdomain: core
  context:
    org:
      id: 1752f41b
      name: Harmony Global Service
      slugName: harmony_global_service
    orgUnit:
      id: 1752f41c
      name: Research Sale division
      slugName: research_sale_division
    package:
      id: 44551ba2
      name: Adeo Search
      slugName: adeo_search
    project:
      area: FR
      id: 1752f41a
      name: Search engine project
      slugName: search_engine_project
    subscription:
      env: prod
      id: 1752f41e
      name: Harmony Global/Research Sale division to Adeo Search
      slugName: the-subscription-for-the-client-1
      type: small

product:
  metadata:
    id: "c8b4d3c4" 
    name: My Product
    externalId: 7efabec7-723e-4f0c-b1ff-693a4172a446
    slugName: my-product # max char 36
    maintainer: 
     teamName: my-team-cram

component:
  env:
    - name: FOO_ENV
      value: bar
  secrets:
    env:
      fromCommonKeys: # commons secrets
        - name: FOO_VAULT
          key: FOO_VAULT
        - name: FILE_JSON
          key: file.json
        - name: FILE_BIN
          key: file.binary
      fromResources: # resources secrets
        fakestorages:
          storage01:
            - name: CONNECTION_STRING_STANDARD
              key: connectionStringStandard
            - name: CONNECTION_STRING_STANDARD_BIS
              key: connectionStringStandard
        kafkatopics:
          cluster:
            - name: KAFKA_URL
              key: url
            - name: KAFKA_USERNAME
              key: username
            - name: KAFKA_PASSWORD
              key: password

          schemaRegistry:
            - name: SCHEMA_REGISTRY_URL
              key: url
            - name: SCHEMA_REGISTRY_USERNAME
              key: username
            - name: SCHEMA_REGISTRY_PASSWORD
              key: password

          topic01:
            - name: TOPIC01_NAME
              key: name
            - name: TOPIC01_ID
              key: id
          topic02:
            - name: TOPIC02_NAME
              key: name
            - name: TOPIC02_ID
              key: id
          topic03:
            - name: TOPIC03_NAME
              key: name
            - name: TOPIC03_ID
              key: id
        postgresqls:
          pg01:
            - name: POSTGRES_USER
              key: PGUSER
            - name: POSTGRES_PWD
              key: PGPASSWORD
            - name: PGHOST
              key: PGHOST
            - name: PGPORT
              key: PGPORT
            - name: PGSSLMODE
              key: PGSSLMODE
    volume:
      mountPath: /app/secrets
      fromCommonKeys: # commons secrets
        - name: FOO_VAULT
          key: FOO_VAULT
        - name: file.json
          key: file.json
        - name: file.binary
          key: file.binary
      fromResources: # resources secrets
        fakestorages:
          storage01:
            - name: CONNECTION_STRING_STANDARD
              key: connectionStringStandard

  image:
    repository: nginx
    tag: 1.23.4

  hpa: 
    minReplicas: 2
    maxReplicas: 5
    metrics:
    - type: Resource
      resource:
        name: cpu
        target:
          type: Utilization
          averageUtilization: 50

  ports:
    main: 80
    admin: 8001

  livenessProbe:
    httpGet:  
      path: /
  
  readinessProbe:
    httpGet:  
      path: /

  isConsumer: true

  routes:
    route-1:
      paths:
        - path: /
